"""Adding visibility to courses + share links

Revision ID: 2ad72662f2b6
Revises: 519cbe32d71d
Create Date: 2026-08-14 13:36:23.097921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad72662f2b6'
down_revision: Union[str, None] = '519cbe32d71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_share_links_course_id'), 'share_links', ['course_id'], unique=False)
    op.add_column('courses', sa.Column('visibilite', sa.String(length=10), server_default=sa.text("'en_cours'"), nullable=False))
    # Autogenerate ne voit pas les CheckConstraint d'un add_column (piège
    # documenté dans CLAUDE.md) : posé à la main, miroir de Course.__table_args__.
    op.create_check_constraint(
        'ck_courses_visibilite',
        'courses',
        "visibilite IN ('public', 'prive', 'en_cours')",
    )
    op.add_column('users', sa.Column('nom_public', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nom_public')
    op.drop_constraint('ck_courses_visibilite', 'courses', type_='check')
    op.drop_column('courses', 'visibilite')
    op.drop_index(op.f('ix_share_links_course_id'), table_name='share_links')
    op.drop_table('share_links')
    # ### end Alembic commands ###
