"""table d'état des jobs de maintenance

Revision ID: 34bb8ae6abf2
Revises: 7d2e91c4a6b8
Create Date: 2026-09-18 11:42:38.058007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34bb8ae6abf2'
down_revision: Union[str, None] = '7d2e91c4a6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_job_state',
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_status', sa.String(length=10), nullable=False),
    sa.Column('last_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_duration_ms', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_runs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("last_status IN ('ok', 'failed', 'skipped')", name='ck_maintenance_job_state_status'),
    sa.CheckConstraint('consecutive_failures >= 0', name='ck_maintenance_job_state_failures_positive'),
    sa.CheckConstraint('last_count >= 0', name='ck_maintenance_job_state_count_positive'),
    sa.CheckConstraint('last_duration_ms >= 0', name='ck_maintenance_job_state_duration_positive'),
    sa.CheckConstraint('total_runs >= 0', name='ck_maintenance_job_state_runs_positive'),
    sa.PrimaryKeyConstraint('job_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_job_state')
    # ### end Alembic commands ###
