"""quota quotidien ia par defaut

Revision ID: 458652f0f3d9
Revises: a1f3c58be201
Create Date: 2026-08-30 14:58:22.549023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458652f0f3d9'
down_revision: Union[str, None] = 'a1f3c58be201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_daily_usage',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jour', sa.Date(), nullable=False),
    sa.Column('appels', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'jour')
    )
    op.add_column('users', sa.Column('ai_quota_appels', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_quota_appels')
    op.drop_table('ai_daily_usage')
    # ### end Alembic commands ###
