"""create subjects table

Revision ID: 5810c28ffd87
Revises: 
Create Date: 2026-07-06 23:53:46.778240

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5810c28ffd87'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=500), nullable=False),
    sa.Column('profondeur', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
              nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
              nullable=False),
    sa.CheckConstraint('parent_id != id', name='ck_subjects_pas_son_propre_parent'),
    sa.CheckConstraint('profondeur >= 0 AND profondeur <= 3', name='ck_subjects_profondeur'),
    sa.ForeignKeyConstraint(['parent_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('parent_id', 'nom', name='uq_subjects_parent_id_nom',
                        postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_subjects_parent_id'), 'subjects', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_parent_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
