"""Adding title and description to blocks

Revision ID: 6c3c07ee9ea3
Revises: 7767d9f0ffe7
Create Date: 2026-07-08 14:23:45.485416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3c07ee9ea3'
down_revision: Union[str, None] = '7767d9f0ffe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('titre', sa.String(length=300), nullable=True))
    op.add_column('blocks', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'description')
    op.drop_column('blocks', 'titre')
    # ### end Alembic commands ###
