"""create courses blocks resources modules tables

Revision ID: 7767d9f0ffe7
Revises: bc43f76cbeac
Create Date: 2026-07-07 18:28:47.678076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7767d9f0ffe7'
down_revision: Union[str, None] = 'bc43f76cbeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_owner_id'), 'courses', ['owner_id'], unique=False)
    op.create_table('course_education_levels',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('education_level_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'education_level_id')
    )
    op.create_index('ix_course_education_levels_education_level_id', 'course_education_levels', ['education_level_id'], unique=False)
    op.create_table('course_subjects',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'subject_id')
    )
    op.create_index('ix_course_subjects_subject_id', 'course_subjects', ['subject_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('nom_original', sa.String(length=255), nullable=False),
    sa.Column('taille', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.String(length=15), server_default='en_attente', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("statut IN ('en_attente', 'disponible')", name='ck_resources_statut'),
    sa.CheckConstraint("type IN ('document', 'image', 'audio', 'video', 'module')", name='ck_resources_type'),
    sa.CheckConstraint('taille >= 0', name='ck_resources_taille_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key', name='uq_resources_s3_key')
    )
    op.create_index(op.f('ix_resources_course_id'), 'resources', ['course_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'ressource') = (resource_id IS NOT NULL)", name='ck_blocks_ressource_coherence'),
    sa.CheckConstraint("type IN ('texte', 'exercice', 'ressource', 'lien')", name='ck_blocks_type'),
    sa.CheckConstraint('position >= 0', name='ck_blocks_position_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blocks_course_id_position', 'blocks', ['course_id', 'position'], unique=False)
    op.create_index(op.f('ix_blocks_resource_id'), 'blocks', ['resource_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('entrypoint', sa.String(length=255), server_default='index.html', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_modules_version_positive'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', name='uq_modules_resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules')
    op.drop_index(op.f('ix_blocks_resource_id'), table_name='blocks')
    op.drop_index('ix_blocks_course_id_position', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_resources_course_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_course_subjects_subject_id', table_name='course_subjects')
    op.drop_table('course_subjects')
    op.drop_index('ix_course_education_levels_education_level_id', table_name='course_education_levels')
    op.drop_table('course_education_levels')
    op.drop_index(op.f('ix_courses_owner_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
