"""exercise submissions

Revision ID: ab20ee453c11
Revises: 68544427ba3d
Create Date: 2026-09-03 19:27:18.765463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab20ee453c11'
down_revision: Union[str, None] = '68544427ba3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('effort', sa.String(length=20), nullable=True),
    sa.Column('revealed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("effort IS NULL OR effort IN ('sufficient', 'insufficient')", name='ck_exercise_submissions_effort'),
    sa.CheckConstraint("kind IN ('answer', 'message')", name='ck_exercise_submissions_kind'),
    sa.CheckConstraint("verdict IS NULL OR verdict IN ('correct', 'partial', 'incorrect', 'none')", name='ck_exercise_submissions_verdict'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_submissions_block_id'), 'exercise_submissions', ['block_id'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_course_id'), 'exercise_submissions', ['course_id'], unique=False)
    op.create_index('ix_exercise_submissions_thread', 'exercise_submissions', ['user_id', 'block_id', 'question_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercise_submissions_thread', table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_course_id'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_block_id'), table_name='exercise_submissions')
    op.drop_table('exercise_submissions')
    # ### end Alembic commands ###
