"""create users and profile association tables

Revision ID: bc43f76cbeac
Revises: b69a6dbfa0b9
Create Date: 2026-07-07 15:43:36.161560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc43f76cbeac'
down_revision: Union[str, None] = 'b69a6dbfa0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('est_prof', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('est_eleve', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('systeme_scolaire', sa.String(length=20), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('onboarded_at IS NULL OR est_prof OR est_eleve', name='ck_users_onboarde_implique_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub', name='uq_users_sub')
    )
    op.create_table('user_education_levels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('education_level_id', sa.UUID(), nullable=False),
    sa.Column('contexte', sa.String(length=10), nullable=False),
    sa.CheckConstraint("contexte IN ('enseigne', 'apprend')", name='ck_user_education_levels_contexte'),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'education_level_id', 'contexte')
    )
    op.create_table('user_subjects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('contexte', sa.String(length=10), nullable=False),
    sa.CheckConstraint("contexte IN ('enseigne', 'apprend')", name='ck_user_subjects_contexte'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject_id', 'contexte')
    )
    op.create_index(op.f('ix_education_levels_systeme'), 'education_levels', ['systeme'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_education_levels_systeme'), table_name='education_levels')
    op.drop_table('user_subjects')
    op.drop_table('user_education_levels')
    op.drop_table('users')
    # ### end Alembic commands ###
