"""preferences de raisonnement ia

Revision ID: bdc4cf611389
Revises: cb7b26f85f15
Create Date: 2026-09-09 13:43:15.862143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc4cf611389'
down_revision: Union[str, None] = 'cb7b26f85f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_reasoning', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ai_reasoning_effort', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_reasoning_effort')
    op.drop_column('users', 'ai_reasoning')
    # ### end Alembic commands ###
