"""rôle de plateforme des utilisateurs

Revision ID: bf482c1b00fb
Revises: 34bb8ae6abf2
Create Date: 2026-09-18 15:05:51.103829

Le canal de contrôle du scheduler vit dans Redis, pas en base (décision 39) :
cette révision n'ajoute que `users.platform_role`. Le CHECK est posé à la main,
autogenerate ne voyant pas une contrainte ajoutée à une table existante.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bf482c1b00fb'
down_revision: Union[str, None] = '34bb8ae6abf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('platform_role', sa.String(length=20), server_default=sa.text("'public'"), nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        'ck_users_platform_role', 'users', "platform_role IN ('public', 'super_admin')"
    )


def downgrade() -> None:
    op.drop_constraint('ck_users_platform_role', 'users', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform_role')
    # ### end Alembic commands ###
