"""cached input tokens

Revision ID: cb7b26f85f15
Revises: ab20ee453c11
Create Date: 2026-09-09 09:03:12.281816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7b26f85f15'
down_revision: Union[str, None] = 'ab20ee453c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('cached_input_tokens', sa.Integer(), nullable=True))
    op.add_column('exercise_submissions', sa.Column('cached_input_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_submissions', 'cached_input_tokens')
    op.drop_column('ai_messages', 'cached_input_tokens')
    # ### end Alembic commands ###
