"""fts recherche j3

Revision ID: feb3a436271b
Revises: 2ad72662f2b6
Create Date: 2026-08-18 17:17:20.967719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feb3a436271b'
down_revision: Union[str, None] = '2ad72662f2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Extension + config FTS française insensible aux accents (J3) ---
    # Exception actée à la règle « pas d'extension Postgres » (arbitrage
    # utilisateur, cf. CLAUDE.md) : unaccent est une extension contrib livrée
    # avec Postgres. CREATE EXTENSION exige un rôle superuser (OK avec le
    # docker-compose ; sur le Pi, pré-créer l'extension à la main si
    # l'utilisateur applicatif ne l'est pas).
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute(
        "CREATE TEXT SEARCH CONFIGURATION public.french_unaccent "
        "(COPY = pg_catalog.french)"
    )
    op.execute(
        """
        ALTER TEXT SEARCH CONFIGURATION public.french_unaccent
        ALTER MAPPING FOR hword, hword_part, word
        WITH public.unaccent, french_stem
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.add_column('courses', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.add_column('users', sa.Column('cherchable', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # --- Fonctions de calcul, PARTAGÉES triggers + backfill ---
    # Une seule définition de « quoi indexer » : le backfill ci-dessous ne
    # peut pas diverger des triggers. Poids : titre cours A, description
    # cours B, titre bloc B, contenu bloc C.
    op.execute(
        """
        CREATE FUNCTION courses_tsvector(titre text, description text)
        RETURNS tsvector
        LANGUAGE sql STABLE AS $$
            SELECT setweight(
                       to_tsvector('public.french_unaccent', coalesce(titre, '')), 'A')
                || setweight(
                       to_tsvector('public.french_unaccent', coalesce(description, '')), 'B')
        $$
        """
    )
    # Champ par champ, JAMAIS le content entier : le corrigé du prof
    # (contrat de block.py) ne doit pas devenir cherchable depuis le régime
    # public. Le garde-fou tests/test_search_api.py scanne ce corps $$…$$.
    op.execute(
        """
        CREATE FUNCTION blocks_tsvector(titre text, description text, content jsonb)
        RETURNS tsvector
        LANGUAGE sql STABLE AS $$
            SELECT setweight(
                       to_tsvector('public.french_unaccent', coalesce(titre, '')), 'B')
                || setweight(
                       to_tsvector('public.french_unaccent',
                           coalesce(description, '') || ' '
                        || coalesce(content->>'markdown', '') || ' '
                        || coalesce(content->>'enonce', '') || ' '
                        || coalesce(content->>'legende', '') || ' '
                        || coalesce((
                               SELECT string_agg(q->>'enonce', ' ')
                               FROM jsonb_array_elements(
                                   CASE WHEN jsonb_typeof(content->'questions') = 'array'
                                        THEN content->'questions'
                                        ELSE '[]'::jsonb END) AS q
                           ), '')
                       ), 'C')
        $$
        """
    )

    # --- Triggers (premiers triggers du repo) ---
    # BEFORE + UPDATE OF : pas de tir sur les bumps updated_at / visibilite /
    # position / preview_settings ; un trigger BEFORE modifie NEW, aucun
    # risque de boucle.
    op.execute(
        """
        CREATE FUNCTION courses_search_vector_trigger() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.search_vector := courses_tsvector(NEW.titre, NEW.description);
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_courses_search_vector
        BEFORE INSERT OR UPDATE OF titre, description ON courses
        FOR EACH ROW EXECUTE FUNCTION courses_search_vector_trigger()
        """
    )
    op.execute(
        """
        CREATE FUNCTION blocks_search_vector_trigger() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.search_vector := blocks_tsvector(NEW.titre, NEW.description, NEW.content);
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_blocks_search_vector
        BEFORE INSERT OR UPDATE OF titre, description, content ON blocks
        FOR EACH ROW EXECUTE FUNCTION blocks_search_vector_trigger()
        """
    )

    # --- Backfill des lignes existantes (mêmes fonctions que les triggers) ---
    op.execute("UPDATE courses SET search_vector = courses_tsvector(titre, description)")
    op.execute(
        "UPDATE blocks SET search_vector = blocks_tsvector(titre, description, content)"
    )

    # --- Index GIN ---
    op.create_index(
        "ix_courses_search_vector", "courses", ["search_vector"], postgresql_using="gin"
    )
    op.create_index(
        "ix_blocks_search_vector", "blocks", ["search_vector"], postgresql_using="gin"
    )


def downgrade() -> None:
    op.drop_index("ix_blocks_search_vector", table_name="blocks")
    op.drop_index("ix_courses_search_vector", table_name="courses")
    op.execute("DROP TRIGGER trg_blocks_search_vector ON blocks")
    op.execute("DROP TRIGGER trg_courses_search_vector ON courses")
    op.execute("DROP FUNCTION blocks_search_vector_trigger()")
    op.execute("DROP FUNCTION courses_search_vector_trigger()")
    op.execute("DROP FUNCTION blocks_tsvector(text, text, jsonb)")
    op.execute("DROP FUNCTION courses_tsvector(text, text)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cherchable')
    op.drop_column('courses', 'search_vector')
    op.drop_column('blocks', 'search_vector')
    # ### end Alembic commands ###
    op.execute("DROP TEXT SEARCH CONFIGURATION public.french_unaccent")
    op.execute("DROP EXTENSION IF EXISTS unaccent")
