"""create education_levels table

Revision ID: ffacdb1757a4
Revises: d72c77c8bf86
Create Date: 2026-07-07 14:12:43.705532

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ffacdb1757a4'
down_revision: str | None = 'd72c77c8bf86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('systeme', sa.String(length=20), nullable=False),
    sa.Column('cite', sa.SmallInteger(), nullable=True),
    sa.Column('age_min', sa.SmallInteger(), nullable=True),
    sa.Column('age_max', sa.SmallInteger(), nullable=True),
    sa.Column('profondeur', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
              nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
              nullable=False),
    sa.CheckConstraint('(age_min IS NULL OR age_min >= 0)'
                       ' AND (age_max IS NULL OR age_max >= 0)'
                       ' AND (age_min IS NULL OR age_max IS NULL OR age_min <= age_max)',
                       name='ck_education_levels_ages'),
    sa.CheckConstraint('cite IS NULL OR (cite >= 0 AND cite <= 8)',
                       name='ck_education_levels_cite'),
    sa.CheckConstraint('parent_id != id', name='ck_education_levels_pas_son_propre_parent'),
    sa.CheckConstraint('profondeur >= 0 AND profondeur <= 1',
                       name='ck_education_levels_profondeur'),
    sa.ForeignKeyConstraint(['parent_id'], ['education_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('systeme', 'parent_id', 'nom',
                        name='uq_education_levels_systeme_parent_id_nom',
                        postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_education_levels_parent_id'), 'education_levels', ['parent_id'],
                    unique=False)
    op.create_index(op.f('ix_education_levels_systeme'), 'education_levels', ['systeme'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_education_levels_parent_id'), table_name='education_levels')
    op.drop_index(op.f('ix_education_levels_systeme'), table_name='education_levels')
    op.drop_table('education_levels')
    # ### end Alembic commands ###
